export const CHANGE_TEMP = 'CHANGE_TEMP';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'; 
export const FETCH_SEARCH_FAIL = 'FETCH_SEARCH_FAIL';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS'

export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY'; 
