export const CHANGE_TEMP = 'CHANGE_TEMP';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS'; 
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY'; 
export const FETCH_CURRENT_WEATHER = 'FETCH_CURRENT_WEATHER';
export const FETCH_CURRENT_WEATHER_START = 'FETCH_CURRENT_WEATHER_START';
export const FETCH_CURRENT_WEATHER_SUCCESS = 'FETCH_CURRENT_WEATHER_SUCCESS';

export const GET_GEO_LOCATION = 'GET_GEO_LOCATION';
export const FETCH_GEO_LOCATION ='FETCH_GEO_LOCATION'; 
export const FETCH_GEO_LOCATION_SUCCESS = 'FETCH_GEO_LOCATION_SUCCESS';
export const FETCH_GEO_LOCATION_FAIL = 'FETCH_GEO_LOCATION_FAIL';

export const FETCH_FORECAST = 'FETCH_FORECAST';
export const FETCH_FORECAST_START = 'FETCH_FORECAST_START';
export const FETCH_FORECAST_SUCCESS = 'FETCH_FORECAST_SUCCESS';

export const SET_FAVORITES = 'SET_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const ADD_FAVORITE = 'REMOVE_FAVORITE';




 
