export const CHANGE_TEMP = 'CHANGE_TEMP';
export const CHANGE_THEME = 'CHANGE_THEME';

export const FETCH_SEARCH = 'FETCH_SEARCH';
export const FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS';
export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';

export const UPDATE_SELECTED_CITY = 'UPDATE_SELECTED_CITY';

export const FETCH_CITY_DATA = 'FETCH_CITY_DATA';
export const FETCH_CITY_DATA_START = 'FETCH_CITY_DATA_START';
export const FETCH_CITY_DATA_SUCCESS = 'FETCH_CITY_DATA_SUCCESS';

export const GET_GEO_LOCATION = 'GET_GEO_LOCATION';
export const FETCH_GEO_LOCATION = 'FETCH_GEO_LOCATION';
export const FETCH_GEO_LOCATION_SUCCESS = 'FETCH_GEO_LOCATION_SUCCESS';
export const FETCH_GEO_LOCATION_FAIL = 'FETCH_GEO_LOCATION_FAIL';

export const SET_FAVORITES = 'SET_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const ADD_FAVORITE = 'REMOVE_FAVORITE';

export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_START = 'FETCH_FAVORITES_START';
export const FETCH_FAVORITES_SUCCESS = 'FETCH_FAVORITES_SUCCESS';
export const CLEAR_FETCHED_FAVORITES = 'CLEAR_FETCHED_FAVORITES';